"""
narrative.py — THE ONLY MODULE WHERE THE LLM IS INVOKED.

Uses Google Gemini (free tier).
Get a free key at: https://aistudio.google.com/app/apikey
Set: export GEMINI_API_KEY=your_key_here
"""
import os, re, json, urllib.request, urllib.error

def _numbers(text): return set(re.findall(r"\d+(?:[.,]\d+)?", text))

def generate_narrative(figures: list[dict], firm_config: dict) -> str:
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        return ""

    summary = json.dumps([
        {"figure": f["figure"], "value": f["value"],
         "status": f["status"], "limit": f["limit"]}
        for f in figures
    ], indent=2)

    prompt = f"""You are a compliance report writer for a Singapore MAS-regulated fixed income fund.

STRICT RULES:
1. Do NOT introduce any number not in the pre-computed figures below.
2. Do NOT modify or restate any figure differently from what you were given.
3. Write ONLY narrative prose — no tables, no calculations.
4. Reference figures by their exact provided value.
5. Keep commentary under 200 words.

Write a compliance summary narrative for the Meridian Fixed Income Fund.
Firm: {firm_config['firm_name']}

Pre-computed figures:
{summary}

Write 3-4 sentences summarising overall compliance status, noting any breaches or at-limit items."""

    payload = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"maxOutputTokens": 300, "temperature": 0.2},
    }).encode("utf-8")

    # Current active free-tier Gemini models (as of 2025)
    models = ["gemini-2.5-flash-lite", "gemini-2.5-flash", "gemini-2.0-flash"]

    for model in models:
        url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
               f"{model}:generateContent?key={api_key}")
        try:
            req = urllib.request.Request(url, data=payload,
                headers={"Content-Type": "application/json"}, method="POST")
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            text = data["candidates"][0]["content"]["parts"][0]["text"]
            print(f"      Narrative generated by {model}")
            return text
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "replace")
            if e.code in (404, 429):
                print(f"      [Narrative] {model} returned {e.code}, trying next model...")
                continue
            print(f"      [Narrative] HTTP {e.code} from {model}: {body[:120]}")
            return ""
        except Exception as e:
            print(f"      [Narrative] Error with {model}: {e}")
            return ""

    print("      [Narrative] All models unavailable. Skipping narrative.")
    return ""

def firewall_check(narrative: str, figures: list[dict]) -> dict:
    if not narrative:
        return {"passed": True, "violations": [], "skipped": True}
    allowed = set()
    for f in figures:
        for field in ["value", "limit", "utilization"]:
            allowed |= _numbers(str(f.get(field) or ""))
    allowed |= {"1","2","3","4","5","7","10","24","25","100"}
    narrative_nums = _numbers(narrative)
    violations = sorted(narrative_nums - allowed)
    return {"passed": len(violations)==0, "violations": violations,
            "narrative_numbers": sorted(narrative_nums), "allowed_numbers": sorted(allowed)}
